version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - PG_USER=postgres
      - PG_HOST=postgres_db
      - PG_DATABASE=whatsapp_crm
      - PG_PASSWORD=postgres_password
      - PG_PORT=5432
      - REDIS_URL=redis://redis_cache:6379
    depends_on:
      - postgres_db
      - redis_cache

  postgres_db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: whatsapp_crm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql

  redis_cache:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
